name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
    sdk: '>=2.19.4 <4.0.0'

dependencies:
    get_it: ^7.1.3
    http: 1.1.0
    flutter:
        sdk: flutter
    carousel_slider: ^4.0.0
    vibration: ^1.8.2

    english_words: ^4.0.0
    provider: ^6.0.0
    firebase_core: ^2.16.0
    firebase_auth: ^4.10.0
    cloud_firestore: ^4.9.2
    get: ^4.6.6

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
