name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
    sdk: '>=2.19.4 <4.0.0'

dependencies:
    get_it: ^7.1.3
    get: ^4.6.6
    http: 1.1.0
    flutter:
        sdk: flutter
    carousel_slider: ^4.0.0
    vibration: ^1.8.2

    english_words: ^4.0.0
    provider: ^6.0.5
    image_picker: ^1.0.4
    firebase_core: ^2.16.0
    firebase_auth: ^4.10.0
    cloud_firestore: ^4.9.2
    firebase_storage: ^11.2.8
    camera: ^0.10.5+5
    path_provider: ^2.1.1
    path: ^1.8.3
    lzstring: ^2.0.0+2
    mockito: ^5.4.2
    socket_io_client: ^2.0.3+1
    audioplayers: ^5.2.0
    rxdart: ^0.27.7
    flutter_localizations:
        sdk: flutter
    intl: ^0.18.1
    flutter_ringtone_player: ^3.2.0
    image: ^4.1.3
    flutter_colorpicker: ^1.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    generate: true
    uses-material-design: true
    assets:
        - assets/
        - assets/sounds/
        - assets/avatar-predefini/
